// 凍肉水產商品資料
// 監控中曾出現的產品編號對照（若不在下方 PRODUCTS 中，在此補充以顯示產品名字）
window.ANALYTICS_CODE_NAMES = {
  "CN-PK-001": "高峰四肉/中國二肉",
  "CN-CK-001": "欣城50+中翼",
  "VN-CF-001": "越南Dai Thanh鯰魚柳",
  "VG-PEA-001": "青豆粒",
  "VG-EDM-001": "毛豆粒",
  "CN-PK-002": "中國大排 5-7條",
  "CN-PK-003": "中國三肉 9-13條",
  "HK-SCY-001": "酸菜魚",
  "HK-NW-001": "牛丸",
  "CN-CH-001": "高峰四肉/中國二肉",
  "BR-BF-001": "巴西牛肉1",
  "BR-BF-002": "巴西牛肉2",
};

// 圖片：在產品物件中加入 images 陣列，路徑相對於 index.html；無則顯示佔位圖

window.PRODUCTS = [
  {
    code: "CN-PK-001",
    name: "高峰四肉/中國二肉",
    images: ["images/高峰四肉.jpg", "images/中國二肉.jpg"],
    category: "中國豬肉",
    specLines: ["高峰四肉3-4塊", "中國二肉6-7塊"],
    priceLines: [
      "300箱以上：$20.2/kg",
      "100–300箱：$20.5/kg",
      "100箱以下：$20.8/kg",
    ],
    price: "300箱以上 $20.2/kg；100–300箱 $20.5/kg；100箱以下 $20.8/kg",
    leadTime: "4月中–6月",
    available: true,
    popularity: 90,
  },
  {
    code: "CN-CK-001",
    name: "欣城50+中翼",
    images: ["images/CN-CK-001-wing.jpeg"],
    category: "中國雞類",
    specLines: ["50+中翼"],
    priceLines: ["$48.0/kg（到取）"],
    price: "$48.0/kg（到取）",
    leadTime: "4月底/5月",
    available: true,
    popularity: 85,
  },
  {
    code: "VN-CF-001",
    name: "越南Dai Thanh鯰魚柳",
    category: "越南水產",
    factory: "Plant：DL 471",
    specLines: ["IQF/IWP Packing"],
    priceLines: [
      "到取價",
      "7成：$7.1/lb",
      "8成：$7.9/lb",
      "10成：$10/lb",
    ],
    price: "7成 $7.1/lb；8成 $7.9/lb；10成 $10/lb",
    packaging: "IQF/IWP Packing",
    leadTime: "5月",
    note: "截盤時間：16/4/2026",
    available: true,
    popularity: 88,
  },
  {
    code: "VG-PEA-001",
    name: "青豆粒",
    category: "蔬菜豆類",
    specLines: ["1kg/包，10kg/箱"],
    packaging: "1kg/包，10kg/箱",
    price: "$14.5/kg",
    leadTime: "5月",
    available: true,
    popularity: 70,
  },
  {
    code: "VG-EDM-001",
    name: "毛豆粒",
    category: "蔬菜豆類",
    specLines: ["1kg/包，10kg/箱"],
    packaging: "1kg/包，10kg/箱",
    price: "$15.8/kg",
    leadTime: "5月",
    available: true,
    popularity: 70,
  },
];
